# Generated by Django 3.1.2 on 2021-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
