# Generated by Django 3.1.2 on 2021-08-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_list_app', '0002_auto_20210827_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_creater',
            new_name='user',
        ),
    ]
