# Generated by Django 3.1.2 on 2021-08-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_list_app', '0005_auto_20210829_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='created',
        ),
    ]
