# Generated by Django 3.1.2 on 2021-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_list_app', '0006_remove_uploadfile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
