# Generated by Django 3.1.2 on 2021-08-29 09:38

from django.db import migrations, models
import score_list_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('score_list_app', '0007_auto_20210829_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='upload',
            field=models.FileField(upload_to='score_list_app/static/', validators=[score_list_app.validators.validate_file_extension]),
        ),
    ]
